[package]
name = "ledzilla_server"
version = "0.1.0"
edition = "2024"

[features]
# default = ["simulator", "led"]
simulator = ["dep:embedded-graphics-simulator"]
led = ["dep:rpi-led-panel"]

[dependencies]
embedded-graphics = "0.8.2"
embedded-graphics-simulator = { version = "0.8.0", optional = true }
log = "0.4.33"
rouille = "3.6.2"
rpi-led-panel = { version = "0.8.1", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_with = "3.21.0"
simple_logger = "5.2.0"
time = "0.3.53"
